[project]
name = "polyfin"
version = "1.0.0"
authors = [
  { name="elhlab", email="elh.git@proton.me" },
]
description = "A transparent proxy for Jellyfin, which allows for multi language libraries."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "aiohttp>=3.14.3",
    "cashews>=7.5.0",
    "multidict>=6.7.1",
    "pydantic>=2.13.4",
    "starlette>=1.6.0",
    "uvicorn>=0.52.3",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=9.1.1",
]

[tool.black]
line-length = 88
target-version = ["py312"]

[project.scripts]
polyfin = "polyfin.main:main"

[tool.uv]
package = true
